package com.iemr.flw.masterEnum;

public enum IncentiveName {

    // ---------------- CHILD HEALTH ----------------
    HBNC_0_42_DAYS(GroupName.CHILD_HEALTH),
    HBYC_QUARTERLY_VISITS(GroupName.CHILD_HEALTH),
    SNCU_LBW_FOLLOWUP(GroupName.CHILD_HEALTH),
    SAM_REFERRAL_NRC(GroupName.CHILD_HEALTH),
    CHILD_DEATH_REPORTING(GroupName.CHILD_HEALTH),
    E_HBNC_CACHAR(GroupName.CHILD_HEALTH),
    MAA_QUARTERLY_MEETING(GroupName.CHILD_HEALTH),
    NATIONAL_DEWORMING_DAY(GroupName.CHILD_HEALTH),
    ORS_DISTRIBUTION(GroupName.CHILD_HEALTH),
    NATIONAL_IRON_PLUS(GroupName.CHILD_HEALTH),
    NIPI_CHILDREN(GroupName.CHILD_HEALTH),

    // ---------------- IMMUNIZATION ----------------
    FULL_IMMUNIZATION_0_1(GroupName.IMMUNIZATION),
    COMPLETE_IMMUNIZATION_1_2(GroupName.IMMUNIZATION),
    DPT_IMMUNIZATION_5_YEARS(GroupName.IMMUNIZATION),
    CHILD_MOBILIZATION_SESSIONS(GroupName.IMMUNIZATION),

    // ---------------- MATERNAL HEALTH ----------------
    ANC_REGISTRATION_1ST_TRIM(GroupName.MATERNAL_HEALTH),
    FULL_ANC(GroupName.MATERNAL_HEALTH),
    COMPREHENSIVE_ABORTION_CARE(GroupName.MATERNAL_HEALTH),
    INST_DELIVERY_HRP(GroupName.MATERNAL_HEALTH),
    EPMSMA_INST_DELIVERY(GroupName.MATERNAL_HEALTH),
    EPMSMA_HRP_IDENTIFIED(GroupName.MATERNAL_HEALTH),
    MATERNAL_DEATH_REPORT(GroupName.MATERNAL_HEALTH),
    MH_MISOPROSTOL(GroupName.MATERNAL_HEALTH),
    MH_EARLY_REG_BANK(GroupName.MATERNAL_HEALTH),
    MH_ANC_3RD_TRIM(GroupName.MATERNAL_HEALTH),
    MH_MOTIVATE_INST_DEL(GroupName.MATERNAL_HEALTH),
    MH_HR_POSTNATAL(GroupName.MATERNAL_HEALTH),

    // ---------------- JSY ----------------
    JSY_1ST_DEL_ANC_RURAL(GroupName.JSY),
    JSY_1ST_DEL_INST_RURAL(GroupName.JSY),
    JSY_2ND_DEL_ANC_RURAL(GroupName.JSY),
    JSY_2ND_DEL_INST_RURAL(GroupName.JSY),
    JSY_3RD_DEL_ANC_RURAL(GroupName.JSY),
    JSY_3RD_DEL_INST_RURAL(GroupName.JSY),
    JSY_4TH_DEL_ANC_RURAL(GroupName.JSY),
    JSY_4TH_DEL_INST_RURAL(GroupName.JSY),
    JSY_ANC_URBAN(GroupName.JSY),
    JSY_INST_URBAN(GroupName.JSY),

    // ---------------- FAMILY PLANNING ----------------
    FP_ANC_MPA1(GroupName.FAMILY_PLANNING),
    FP_ANC_MPA2(GroupName.FAMILY_PLANNING),
    FP_ANC_MPA3(GroupName.FAMILY_PLANNING),
    FP_ANC_MPA4(GroupName.FAMILY_PLANNING),
    FP_ANC_MPA5(GroupName.FAMILY_PLANNING),
    FIRST_SECOND_CHILD_GAP(GroupName.FAMILY_PLANNING),
    FP_DELAY_2Y(GroupName.FAMILY_PLANNING),
    FP_LIMIT_2CHILD(GroupName.FAMILY_PLANNING),
    FP_PPIUCD(GroupName.FAMILY_PLANNING),
    FP_PAIUCD(GroupName.FAMILY_PLANNING),
    FP_CONDOM(GroupName.FAMILY_PLANNING),
    FP_ORALPILLS(GroupName.FAMILY_PLANNING),
    FP_EC(GroupName.FAMILY_PLANNING),
    FP_FEMALE_STER(GroupName.FAMILY_PLANNING),
    FP_PPS(GroupName.FAMILY_PLANNING),
    FP_MINILAP(GroupName.FAMILY_PLANNING),
    FP_MALE_STER(GroupName.FAMILY_PLANNING),
    FP_EC_SURVEY(GroupName.FAMILY_PLANNING),
    FP_SAAS_BAHU(GroupName.FAMILY_PLANNING),
    FP_NP_KIT(GroupName.FAMILY_PLANNING),

    // ---------------- ADOLESCENT HEALTH ----------------
    AH_SANITARY(GroupName.ADOLESCENT_HEALTH),
    AH_PEER_ED(GroupName.ADOLESCENT_HEALTH),
    AH_MOBILIZE(GroupName.ADOLESCENT_HEALTH),

    // ---------------- ASHA ROUTINE ----------------
    ASHA_MONTHLY_ROUTINE(GroupName.ASHA_MONTHLY_ROUTINE),

    // ---------------- UMBRELLA PROGRAMMES ----------------
    NPCB_GOVT_CATARACT(GroupName.UMBRELLA_PROGRAMMES),
    NPCB_PRIVATE_CATARACT(GroupName.UMBRELLA_PROGRAMMES),
    DSTB_TREATMENT(GroupName.UMBRELLA_PROGRAMMES),
    DRTB_TREATMENT(GroupName.UMBRELLA_PROGRAMMES),
    INFORMANT_INCENTIVE(GroupName.UMBRELLA_PROGRAMMES),
    TPT_PROVIDING(GroupName.UMBRELLA_PROGRAMMES),
    BANK_ACCOUNT_NPY(GroupName.UMBRELLA_PROGRAMMES),
    HOUSE_TO_HOUSE_SURVEY(GroupName.UMBRELLA_PROGRAMMES),
    NLEP_TRAINING(GroupName.UMBRELLA_PROGRAMMES),
    NLEP_CASE_DETECTION(GroupName.UMBRELLA_PROGRAMMES),
    NLEP_PB_TREATMENT(GroupName.UMBRELLA_PROGRAMMES),
    NLEP_MB_TREATMENT(GroupName.UMBRELLA_PROGRAMMES),
    LEPROSY_PARTIAL_ASHA(GroupName.UMBRELLA_PROGRAMMES),
    NVBDCP_SLIDE_COLLECTION(GroupName.UMBRELLA_PROGRAMMES),
    NVBDCP_MALARIA_TREATMENT(GroupName.UMBRELLA_PROGRAMMES),
    AES_JE_REFERRAL(GroupName.UMBRELLA_PROGRAMMES),
    DENGUE_CHIKUNGUNYA(GroupName.UMBRELLA_PROGRAMMES),
    NIDDCP_SALT_TEST(GroupName.UMBRELLA_PROGRAMMES),

    // ---------------- NCD ----------------
    NCD_POP_ENUMERATION(GroupName.NCD),
    NCD_FOLLOWUP_TREATMENT(GroupName.NCD),
    NCD_NEW_PATIENT_MEDICATION_SUPPORT(GroupName.NCD),

    // ---------------- ADDITIONAL INCENTIVE ----------------
    ADDITIONAL_ASHA_INCENTIVE(GroupName.ADDITIONAL_INCENTIVE),

    // ---------------- OTHER INCENTIVES ----------------
    ABHA_ID_CREATION(GroupName.OTHER_INCENTIVES),
    MOBILE_BILL_REIMB(GroupName.OTHER_INCENTIVES),

    // ---------------- ACTIVITY ----------------
    ANC_FOUR_CHECKUPS_SUPPORT(GroupName.ACTIVITY),
    INST_DELIVERY_ESCORT(GroupName.ACTIVITY),
    FILARIASIS_MEDICINE_DISTRIBUTION(GroupName.ACTIVITY),
    VHND_PARTICIPATION(GroupName.ACTIVITY),
    CLUSTER_MEETING(GroupName.ACTIVITY),
    VHSNC_MEETING(GroupName.ACTIVITY),
    MITANIN_REGISTER(GroupName.ACTIVITY),
    HWC_REFERRAL_10_CASES(GroupName.ACTIVITY),
    LACTATING_MOTHERS_HOME_VISIT(GroupName.ACTIVITY),
    MITANIN_REGISTER_5_INFO_FILL(GroupName.ACTIVITY),
    HIGH_RISK_POSTPARTUM_HEALTH_CHECK(GroupName.ACTIVITY),
    MOSQUITO_NET_DISTRIBUTION_MOBILIZATION(GroupName.ACTIVITY),
    HIGH_RISK_POSTPARTUM_CARE(GroupName.ACTIVITY),
    MONTHLY_HONORARIUM(GroupName.ACTIVITY),
    FULL_ANC_45(GroupName.ACTIVITY),
    MH_MOTIVATE_INST_DEL_46(GroupName.ACTIVITY);

    private final GroupName groupName;

    IncentiveName(GroupName groupName) {
        this.groupName = groupName;
    }

    public GroupName getGroupName() {
        return groupName;
    }
}
