fhir-url = ${FHIR_URL}
tm-url = ${TM_URL}

##--------------------------------------------## Primary db-------------------------------------------------------------------

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

##--------------------------------------------## Secondary db-------------------------------------------------------------------

secondary.datasource.username=${DATABASE_IDENTITY_USERNAME}
secondary.datasource.password=${DATABASE_IDENTITY_PASSWORD}
secondary.datasource.url=${DATABASE_IDENTITY_URL}
secondary.datasource.driver-class-name=com.mysql.jdbc.Driver

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#ELK logging file name
logging.path=logs/
logging.file.name=${FLW_API_LOGGING_FILE_NAME}

jwt.secret=${JWT_SECRET_KEY}

# Redis Config
spring.redis.host=${REDIS_HOST}

#### SMS Configuration
send-sms=${SEND_SMS}
source-address=${SMS_CONSENT_SOURCE_ADDRESS}
sms-username=${SMS_USERNAME}
sms-password=${SMS_PASSWORD}

send-message-url=${SMS_MESSAGE_URL}
project-url=${PROJECT_URL}
