package com.iemr.flw.dto.identity;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.sql.Timestamp;

@Data
@Getter
@Setter
public class CbacDTO {
    private Long cbacDetailsId;
    private Long beneficiaryRegId;
    private String cbacAge;
    private Integer cbacAgePosi;
    private String cbacAlcohol;
    private Integer cbacAlcoholPosi;
    private String cbacAntitbdrugs;
    private Integer cbacAntitbdrugsPos;
    private String cbacBleedingafterintercourse;
    private Integer cbacBleedingafterintercoursePos;
    private String cbacBleedingaftermenopause;
    private Integer cbacBleedingaftermenopausePos;
    private String cbacBleedingbtwnperiods;
    private Integer cbacBleedingbtwnperiodsPos;
    private String cbacBlooddischage;
    private Integer cbacBlooddischagePos;
    private String cbacBloodsputum;
    private Integer cbacBloodsputumPos;
    private String cbacChangeinbreast;
    private Integer cbacChangeinbreastPos;
    private String cbacCoughing;
    private Integer cbacCoughingPos;
    private String cbacDifficultyinmouth;
    private Integer cbacDifficultyinmouthPos;
    private String cbacFamilyhistory;
    private Integer cbacFamilyhistoryPosi;
    private String cbacFivermore;
    private Integer cbacFivermorePos;
    private String cbacFoulveginaldischarge;
    private Integer cbacFoulveginaldischargePos;
    private String cbacHistoryoffits;
    private Integer cbacHistoryoffitsPos;
    private String cbacLoseofweight;
    private Integer cbacLoseofweightPos;
    private String cbacLumpinbreast;
    private Integer cbacLumpinbreastPos;
    private String cbacNightsweats;
    private Integer cbacNightsweatsPos;
    private String cbacPa;
    private Integer cbacPaPosi;
    private Integer cbacReferpatientMo;
    private String cbacSmoke;
    private Integer cbacSmokePosi;
    private String cbacSortnesofbirth;
    private Integer cbacSortnesofbirthPos;
    private Integer cbacSputemcollection;
    private String cbacSufferingtb;
    private Integer cbacSufferingtbPos;
    private String cbacTbhistory;
    private Integer cbacTbhistoryPos;
    private String cbacToneofvoice;
    private Integer cbacToneofvoicePos;
    private String cbacTracingAllFm;
    private String cbacUicers;
    private Integer cbacUicersPos;
    private String cbacWaist;
    private Integer cbacWaistPosi;
    private Long houseoldId;
    private Integer countryid;
    private Integer stateid;
    private Integer districtid;
    private String districtname;
    private Integer villageid;
    private Integer serverUpdatedStatus;
    private Integer totalScore;
    private String cbacPainWhileChewing;
    private Integer cbacPainWhileChewingPosi;
    private String cbacAnyThickendSkin;
    private Integer cbacAnyThickendSkinPosi;
    private String cbacClawingOfFingers;
    private Integer cbacClawingOfFingersPosi;
    private String cbacDiffHoldingObj;
    private Integer cbacDiffHoldingObjPosi;
    private String cbacFeelingDown;
    private Integer cbacFeelingDownPosi;
    private Integer cbacFeelingDownScore;
    private String cbacFuelUsed;
    private Integer cbacFuelUsedPosi;
    private String cbacGrowthInMouth;
    private Integer cbacGrowthInMouthPosi;
    private String cbacHyperPigmentedPatch;
    private Integer cbacHyperPigmentedPatchPosi;
    private String cbacInabilityCloseEyelid;
    private Integer cbacInabilityCloseEyelidPosi;
    private String cbacLittleInterest;
    private Integer cbacLittleInterestPosi;
    private Integer cbacLittleInterestScore;
    private String cbacNodulesOnSkin;
    private Integer cbacNodulesOnSkinPosi;
    private String cbacNumbnessOnPalm;
    private Integer cbacNumbnessOnPalmPosi;
    private String cbacOccupationalExposure;
    private Integer cbacOccupationalExposurePosi;
    private String cbacTinglingOrNumbness;
    private Integer cbacTinglingOrNumbnessPosi;
    private String cbacWeeknessInFeet;
    private Integer cbacWeeknessInFeetPosi;
    private String suspectedHrp;
    private String suspectedNcd;
    private String suspectedTb;
    private String suspectedNcdDiseases;
    private String confirmedNcd;
    private String confirmedHrp;
    private String confirmedTb;
    private String confirmedNcdDiseases;
    private String diagnosisStatus;
    private Boolean deleted;
    private String processed;
    private String createdBy;
    private Timestamp createdDate;
    private Boolean reserved;
    private String reservedFor;
    private String reservedOn;
    private Integer reservedById;
    private String modifiedBy;
    private Timestamp lastModDate;
    private Long vanSerialNo;
    private Integer vanId;
    private String vehicalNo;
    private Integer parkingPlaceId;
    private String syncedBy;
    private Timestamp syncedDate;
    private Integer providerServiceMapId;
    private Integer deviceId;
}
